//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourismWeb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TourismDBEntities : DbContext
    {
        public TourismDBEntities()
            : base("name=TourismDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_ContextFactor> tbl_ContextFactor { get; set; }
        public DbSet<tbl_ContextFactorRelation> tbl_ContextFactorRelation { get; set; }
        public DbSet<tbl_TourismDomain> tbl_TourismDomain { get; set; }
        public DbSet<tbl_TourismDomainRelation> tbl_TourismDomainRelation { get; set; }
        public DbSet<tbl_User> tbl_User { get; set; }
        public DbSet<tbl_UserPreferences> tbl_UserPreferences { get; set; }
        public DbSet<tbl_POI> tbl_POI { get; set; }
    }
}
