//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TourismWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UserPreferences
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int DomainId { get; set; }
        public Nullable<int> ContextFactorId { get; set; }
        public double PreferenceValue { get; set; }
        public double ConfidenceValue { get; set; }
    
        public virtual tbl_ContextFactor tbl_ContextFactor { get; set; }
        public virtual tbl_TourismDomain tbl_TourismDomain { get; set; }
        public virtual tbl_User tbl_User { get; set; }
    }
}
